### ISSUE TITLE
[Feature request]: Add details to tab click event

### ISSUE THREAD

**Issue by liviakuenzli** [sbb-design-systems/lyne-components#1351]
### Request type

Request for enhancement of a component

### Functionality

When clicking a tab-title, the tab-group is emitting an event.
However, the event is lacking details; e.g. we do not know which item has been clicked.
We would have to go through all the children and find the active one.

We propose to instead have the new activeIndex/tab-title element directly in the Event (event.details).

### Is there a design proposal?

No

### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the issue tracker for an issue that matches the one I want to file, without success.

**Comment by jeripeierSBB** [comment]
Closed by #2744
