### ISSUE TITLE
[Bug]: SbbDatepicker - sbb-invalid does not work in React Components

### ISSUE THREAD

**Issue by k-luise** [sbb-design-systems/lyne-components#1851]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/lyne-design-system/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### It affects the following packages

Components

### Which version of Lyne Components are you using

0.35.18

### Input mode

None

### What happened?

When using a SbbDatepicker in a SbbFormField it is not possible to display the error state with "class="sbb-invalid""  .  

There should be a red frame around the input and the text should be red also.

### Steps to reproduce the issue

Use the following code: 
 ```
  <SbbFormField>
     <SbbDatepickerPreviousDay />
     <SbbDatepickerToggle />
     <SbbDatepicker />
     <input class="sbb-invalid" data-testid="date input" />
     <SbbDatepickerNextDay />
   </SbbFormField>
```

**Comment by jeripeierSBB** [comment]
In browser it's working. @k-luise Will update if she has more information.

**Comment by kyubisation** [comment]
With https://github.com/lyne-design-system/lyne-components/blob/master/src/components/sbb-datepicker/sbb-datepicker.tsx#L242 it is never checked, whether the new date is actually valid and the `sbb-invalid` is removed anyway
