### ISSUE TITLE
[Feature request]: Tables

### ISSUE THREAD

**Issue by liviakuenzli** [sbb-design-systems/lyne-components#2038]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/lyne-design-system/projects/4) for an issue that matches the one I want to file, without success.

### Request type

Request for a new component

### It affects the following packages

Design Tokens

### Functionality

We would like to have stylings for tables! :)

We want to be able to add tables to content on AEM pages and within accordions. 

Our Specification: https://confluence.sbb.ch/pages/viewpage.action?pageId=2173010559

See also: https://www.figma.com/file/oA9B5W6w0449gtItDzLS86/00%3A-Components?type=design&node-id=21228%3A410640&mode=design&t=rAE9E3pnXM61TEyz-1

### Link to design proposal file

https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?type=design&node-id=10643%3A326841&mode=design&t=iSHLVhCa2b2pfyhn-1

**Comment by kyubisation** [comment]
Implemented via #2715
