### ISSUE TITLE
[Feature request]: Video Container

### ISSUE THREAD

**Issue by liviakuenzli** [sbb-design-systems/lyne-components#2039]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/master/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/master/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/lyne-design-system/projects/4) for an issue that matches the one I want to file, without success.

### Request type

Request for a new component

### It affects the following packages

Components

### Functionality

We would like to be able to add videos within the AEM content.
We suggest that you provide the overlay container and the custom button.

Our Specification: https://confluence.sbb.ch/pages/viewpage.action?pageId=2169770982
Current Implementation (example): https://www.sbb.ch/de/fahrplan/reisehinweise/nachhaltig-reisen/mehrweg.html

Note: The Figma link doesn't look so good. Needs checking by UX.

### Link to design proposal file

https://www.figma.com/design/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?node-id=11917-458794&t=5sckUqDP5QxEQfF4-11

**Comment by kyubisation** [comment]
After careful consideration, we would like to reject the implementation of the video container on our side.
We feel that we cannot reduce the complexity of the use case with our implementation and would provide almost no value.
