### ISSUE TITLE
[Feature request]: Hero teaser with paid content chip (interim solution)

### ISSUE THREAD

**Issue by florianstuerzinger** [sbb-design-systems/lyne-components#2602]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/main/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/main/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/lyne-design-system/projects/4) for an issue that matches the one I want to file, without success.

### Request type

Request for enhancement of a component

### It affects the following packages

Components

### Functionality

Hero Teaser needs a new variant. 

The interim solution is the hero teaser as it is today, plus paid content chip. The final solution includes 1 or 2 partner logos floating over the image.

### Link to design proposal file

https://www.figma.com/file/FwQzAhDa5jjtb3boC16GYi/Marketing%2FMonetarisierung?type=design&node-id=9749%3A16590&mode=design&t=33JuW6rnPuQdKhO0-1

**Comment by mcilurzo** [comment]
figma component: https://www.figma.com/design/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?node-id=30086-43164&t=CJIkbe4AMsoNsaWp-11

**Comment by jeripeierSBB** [comment]
Closed by #2949
