### ISSUE TITLE
[Feature request]: Teaser products

### ISSUE THREAD

**Issue by florianstuerzinger** [sbb-design-systems/lyne-components#2622]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/lyne-design-system/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/lyne-design-system/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/lyne-design-system/projects/4) for an issue that matches the one I want to file, without success.

### Request type

Request for a new component

### It affects the following packages

Components

### Functionality

Should be available in 2 variants, action / no action, similar to the card component. 

### Link to design proposal file
https://www.figma.com/design/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?m=auto&node-id=38378-181176&t=ovyey8p2lgclMnBd-1

https://www.figma.com/design/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?node-id=38653-53875&t=ovyey8p2lgclMnBd-11

https://www.figma.com/design/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?node-id=40870-175704&t=ovyey8p2lgclMnBd-11

**Comment by mcilurzo** [comment]
figma component: https://www.figma.com/design/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?node-id=38378-181176&t=CJIkbe4AMsoNsaWp-11
