### ISSUE TITLE
Selection-Panel: Size S

### ISSUE THREAD

**Issue by TomMenga** [sbb-design-systems/lyne-components#2696]
https://www.figma.com/file/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?type=design&node-id=30172%3A393269&mode=design&t=aBVGHDIkLF2bjfjV-1

**Comment by DavideMininni-Fincons** [comment]
The link in the first comment opens the figma's welcome page
@mcilurzo is this other link correct for panel size s?
https://www.figma.com/design/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?node-id=32781-125169&t=VUoBTcrBwZbgDcg0-4

**Comment by mcilurzo** [comment]
> The link in the first comment opens the figma's welcome page @mcilurzo is this other link correct for panel size s? https://www.figma.com/design/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?node-id=32781-125169&t=VUoBTcrBwZbgDcg0-4

selection panel: 
https://www.figma.com/design/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?node-id=40073-87119&t=TcNghjtFqT45d53X-11
selection panel group:
https://www.figma.com/design/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?node-id=40073-87237&t=TcNghjtFqT45d53X-11
