### ISSUE TITLE
[Bug]: Angular - menu flickers after first time opening

### ISSUE THREAD

**Issue by xXNickznXx** [sbb-design-systems/lyne-components#2701]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### It affects the following packages

Components

### Which version of Lyne Components are you using

0.51.1

### Input mode

None

### What happened?

Reproduction: https://stackblitz.com/edit/lyne-menu-broken-with-zone-js0-14-6?file=src%2Fmain.ts,src%2Fmain.html

In an angular project with [zone.js@0.14.6](https://github.com/angular/angular/blob/main/packages/zone.js/CHANGELOG.md) the menu starts flickering after the first time opening it. With zone.js@0.14.5 it worked without a problem.

### Steps to reproduce the issue

1. Click header-button or normal button
2. Click anywhere so menu closes
3. Click anywhere again

Result: Menu flickers

**Comment by jeripeierSBB** [comment]
Created an issue at Angular: https://github.com/angular/angular/issues/56148

**Comment by xXNickznXx** [comment]
Angular issue has been fixed and a new zone.js version has been released that fixes this issue
