### ISSUE TITLE
[Bug]: sbb-dialog-content partly covered (sbb.ch Mobile timetable settings)

### ISSUE THREAD

**Issue by SarahWigger** [sbb-design-systems/lyne-components#2716]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### It affects the following packages

Components

### Operating system

iOS

### Browser / Browser version

Safari

### Input mode

Touch

### What happened?

On the mobile version sbb.ch, it's not possible to activate the toggle "Alternative connections" in the timetable settings as this is partly covered by the dialog action buttons.

### Steps to reproduce the issue

1. Visit sbb.ch on a mobile device
2. Open the timetable settings
3. Try to activate the toggle at the bottom ("Alternative connections")

**Comment by jeripeierSBB** [comment]
Closed by #2637, please update lyne

**Comment by jeripeierSBB** [comment]
Included in Lyne [0.51.0](https://github.com/sbb-design-systems/lyne-components/compare/v0.50.2...v0.51.0)
