### ISSUE TITLE
story: alert should have same fade out animation on close as notification

### ISSUE THREAD

**Issue by jeripeierSBB** [sbb-design-systems/lyne-components#2745]

**Comment by TomMenga** [comment]
I have a couple of questions/topics to discuss:

1.  In the current implementation, the alert has no close API. When clicking the closing button, it just emits a `requestDismissal`. Proposal: 

  - remove the requestDismissal event
  - Add a cancellable `willClose` and a `didOpen` event
  - Expose a `close` method that will be called automatically when clicking the closing button

2. The `animation` property type default change from `open` to `all` (as the `sbb-notification`)

These changes would both generate a breaking change
