### ISSUE TITLE
Header: Size S

### ISSUE THREAD

**Issue by mcilurzo** [sbb-design-systems/lyne-components#2774]

**Comment by DavideMininni-Fincons** [comment]
Hello @mcilurzo, is there a Figma link for this story?

**Comment by jeripeierSBB** [comment]
> Hello @mcilurzo, is there a Figma link for this story?

Hi @DavideMininni-Fincons It's on the normal Figma of lyne components, but not yet tagged. Scroll to the right side, and there the lower part is size s.
https://www.figma.com/design/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?m=auto&node-id=1220-686725

**Comment by jeripeierSBB** [comment]
<img width="721" alt="Bildschirmfoto 2024-08-27 um 12 57 32" src="https://github.com/user-attachments/assets/54d3a9cc-e259-402b-9cb5-3ccca373d6f1">
