### ISSUE TITLE
[Feature request]: Notification - Icon optional

### ISSUE THREAD

**Issue by florianstuerzinger** [sbb-design-systems/lyne-components#2801]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/4) for an issue that matches the one I want to file, without success.

### Request type

Request for enhancement of a component

### It affects the following packages

Components

### Functionality

The icon in the notification should be optional so that it can be hidden if desired. This applies to every variant of the notification.

A visual solution is still needed for Zero-Micro.

### Link to design proposal file

https://www.figma.com/design/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?node-id=40238-98120&t=LB01gUzQgMFbsuXm-11

**Comment by kyubisation** [comment]
Implemented via #2815
