### ISSUE TITLE
[Bug]: dialog and header not working together on mobile

### ISSUE THREAD

**Issue by tobiasBlaser** [sbb-design-systems/lyne-components#2804]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### It affects the following packages

Components

### Which version of Lyne Components are you using

1.0.0

### Operating system

Sonoma 14.2.1

### Browser / Browser version

Chrome 

### Input mode

None

### What happened?

We Use both the header and the dialog component in our app. In the desktop version this works finde but as you can see in the mobile version the top part of the dialog gets covered by the header.

I tried to add a cheeky fix by adding a margin/padding to the dialog but this didn't work either.

It would be nice if there was an option in the dialog to let it "start" below the header

![Bildschirmfoto 2024-06-21 um 15 43 04](https://github.com/sbb-design-systems/lyne-components/assets/37703134/5c259230-7f08-4af0-a200-88359b258bf8)

### Steps to reproduce the issue

Add a header to an web-app
Add a dialog to an web-app
Open the web-app in the mobile view

An example of this can be found here:
https://knotenkenntnisse-dev.app.sbb.ch/

Drag up the map sidebar
Click on the "Ortungsdiensteinstellungen" link
The dialog that is buggy should open

**Comment by jeripeierSBB** [comment]
There seems to be a problem with z-index on the sidebar of the map-container (set by Lyne). needs fix on map-container.
