### ISSUE TITLE
[Bug]: Nested tab groups don't work via dialog

### ISSUE THREAD

**Issue by sandrooco** [sbb-design-systems/lyne-components#2814]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### It affects the following packages

Components

### Which version of Lyne Components are you using

1.0.0

### Operating system

macOS 14.5

### Browser / Browser version

all

### Input mode

Mouse/Keyboard

### What happened?

I have a case where a button inside a tab group opens a dialog which has a tab group in it. The "inner" tab group does not show up. The elements are properly in the DOM but they don't seem to be properly instantiated as lyne element. My guess is that the elements aren't properly instantiated because the second tab group is already a child of an instance.

This happens in an Angular project, though I am not sure if it's dependent on that.
Also, I'm fully aware that this isn't your typical use case for nested tab groups, I hope the difference is clear.

### Steps to reproduce the issue

1. [Open the Stackblitz example](https://stackblitz.com/edit/angular-at-ktmnsn?file=src%2Fmain.ts,src%2Fapp%2Finner%2Finner.component.html)
2. Click the button "open dialog"
3. there won't be a tab group in the dialog

### Relevant log output

```shell
none - there are no errors showing up
```

**Comment by dauriamarco** [comment]
Hi @sandrooco, thanks for your report. We are planning a slight refactor of the nested tab group logic to make it more stable. However, in cases like yours, we recommend moving the dialog with the inner tab group outside the outer tab group, so that the tab group inside the dialog is not considered "nested" and it will be displayed. Let me know if this can be working solution for you 🙂

**Comment by sandrooco** [comment]
Hi @dauriamarco, thanks for your quick feedback and the ongoing work in #2816. Do you expect these changes to fully clear my situation? If yes, I wouldn't invest in implementing a workaround and simply wait for the next release. :)

**Comment by sandrooco** [comment]
Thanks @dauriamarco & @jeripeierSBB once again for an ultra fast fix time. It works perfectly fine with 1.1.0/1.2.0. 🎉
