### ISSUE TITLE
[Bug]: tab-content pseudo-elements create scrollbar inside map-container

### ISSUE THREAD

**Issue by xXNickznXx** [sbb-design-systems/lyne-components#2835]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### It affects the following packages

Components

### Which version of Lyne Components are you using

1.0.0

### Input mode

None

### What happened?

Found a bug on a mobile-sized screen when combining map-container with tab-group. An unnecessary scrollbar ist shown.
Reproduction: https://stackblitz.com/edit/tab-content-after-creates-scrollbar-inside-map-container?file=src%2Fmain.html

After some testing it seems to be a combination of 2 issues related to this mixin: [src/elements/tabs/tab-group/tab-group.scss#L21](https://github.com/sbb-design-systems/lyne-components/blob/main/src/elements/tabs/tab-group/tab-group.scss#L21)

One is that the `::after` pseudo-element still occupies space underneath the tab-content.
This could be solved by adding `overflow: hidden` to the mixin

The second is that the height which is set here: [src/elements/tabs/tab-group/tab-group.ts#L247](https://github.com/sbb-design-systems/lyne-components/blob/main/src/elements/tabs/tab-group/tab-group.ts#L247) is too small because the margin-top of the paragraph inside isnt included.
This can also be seen in the [storybook](https://lyne-storybook.app.sbb.ch/?path=/docs/elements-sbb-tab-sbb-tab-group--docs#default%20tabs%20size%20l) by changing to "Tab title four" the scrollbar appears.
This could be solved by moving the mixin from the tab-group to the tab itself.

### Steps to reproduce the issue

-

**Comment by jeripeierSBB** [comment]
Thanks for the hints to solve the issue :)
