### ISSUE TITLE
[Feature request]: Container with image in background and larger padding top & bottom

### ISSUE THREAD

**Issue by florianstuerzinger** [sbb-design-systems/lyne-components#2854]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/4) for an issue that matches the one I want to file, without success.

### Request type

Request for enhancement of a component

### It affects the following packages

Components

### Functionality

A variant for the container with an image in the background is required. 
The image should cover the entire width, with a maximum width of 1440px. In addition, for this and only for this variant, the padding top and botton within the image should be increased to XXL (instead of L).

### Link to design proposal file

[_Figma Lyne_](https://www.figma.com/design/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?m=auto&node-id=38441-10245&t=ovOCTWn5FpuTXMxy-1)

**Comment by jeripeierSBB** [comment]
Closed by #2963
