### ISSUE TITLE
[Bug]: focus on disabled buttons

### ISSUE THREAD

**Issue by LEGlism** [sbb-design-systems/lyne-components#2862]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Accessibility

### It affects the following packages

Components

### Which version of Lyne Components are you using

1.2.0

### Operating system

Windows 10

### Browser / Browser version

Chrome  126.0.6478.127

### Input mode

Mouse/Keyboard

### What happened?

At this moment disabled Buttons are not focusable for blind users. You can overwrite this with the tabIndex but this is not working in the DialogActions.
They should be focusable aswell, so that blind users can get information about the status. 
I think there should be  a prop to make this possible.

### Steps to reproduce the issue

1. disabled button on view
2. try to tab to a button
you cant tab to the disabled button

--------------------------

## Implementation Details

- Remove tabindex logic for disabled buttons (all types of buttons, but not form elements)
- Add accessibility documentation for button components to recommend adding aria references to describe why the button is disabled (from consumer side)

**Comment by kyubisation** [comment]
Quick update: We are considering changing the implementation, but first we need to research the topic not to make it worse.

**Comment by kyubisation** [comment]
Resources:

- https://advancedbytez.com/make-disabled-buttons-accessible/
- https://dev.to/josefine/making-disabled-buttons-more-accessible-21ih
