### ISSUE TITLE
bug: hydration of popover causes problems

### ISSUE THREAD

**Issue by feerglas** [sbb-design-systems/lyne-components#2875]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### It affects the following packages

Components

### Which version of Lyne Components are you using

1.2.1

### Operating system

MacOS 14.3

### Browser / Browser version

Chrome 125.0.6422.113

### Input mode

None

### What happened?

In `sbb-popover` a JavaScript error is thrown after SSR only if attribute `hover-trigger` is used. The error is not thorwn if the `hover-trigger` attribute is not used.

### Steps to reproduce the issue

open https://codesandbox.io/p/devbox/sbb-automcomplete-forked-v575qq
make sure the server is running, otherwise run npm start on the terminal.
open the preview in a new tab
open the browser console to see the JavaScript error

### Relevant log output

```shell
hydrate-lit-html.js:6 Uncaught (in promise) Error: Hydration value mismatch: Primitive found where TemplateResult expected. This usually occurs due to conditional rendering that resulted in a different value or template being rendered between the server and client.
    at u (hydrate-lit-html.js:6:2836)
    at f (hydrate-lit-html.js:6:649)
    at s.update (lit-element-hydrate-support.js:1:1227)
    at s.performUpdate (reactive-element.js:6:5503)
    at s.scheduleUpdate (reactive-element.js:6:4980)
    at s._$ET (reactive-element.js:6:4879)
```

**Comment by jeripeierSBB** [comment]
Probably caused by line 230
`this._hoverTrigger = this.hoverTrigger && !window.matchMedia('(pointer: coarse)').matches;`
Need to be fixed :)
