### ISSUE TITLE
Adding a notification to the lead container

### ISSUE THREAD

**Issue by florianstuerzinger** [sbb-design-systems/lyne-components#2932]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/4) for an issue that matches the one I want to file, without success.

### Request type

Request for enhancement of a component

### It affects the following packages

Components

### Functionality

It should be possible to place a notification between the text and placeholder in the lead container. The notification is hidden internally and is located after the space between the text and placeholder. If a notification is active, an additional XXXS space appears below the placeholder.

### Link to design proposal file
https://www.figma.com/design/9r6xSfNmEfCFxl1yFYedrj/Lyne-Components?node-id=42557-18520&t=aLhCMITI5UDPhF0z-11

**Comment by jeripeierSBB** [comment]
We could add an example and probably another css helper class (like for the other spacings in the lead-container)
