### ISSUE TITLE
[Bug]: Menu scroll after navigation

### ISSUE THREAD

**Issue by nlueem** [sbb-design-systems/lyne-components#2967]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### It affects the following packages

Components

### Which version of Lyne Components are you using

1.0.0

### Operating system

Windows 10

### Browser / Browser version

Microsoft Edge;v="126"

### Input mode

Mouse/Keyboard

### Additional settings

Angular 17.3

### What happened?

When navigating via a link or button within the menu, the styles and the data-sbb-scroll-disabled attribute are not removed from the body element. The menu contains multiple sections.

### Steps to reproduce the issue

1. click on sbb-navigation-button: 
  ```html
  <sbb-navigation trigger="menu-trigger" *transloco="let t">
    <sbb-navigation-marker>
      <sbb-navigation-button aria-current="page" id="menu-section-1">
        {{ t("menu.my-services.title") }}
      </sbb-navigation-button>
      <sbb-navigation-button id="nav-section-2"
        >{{ t("menu.my-data.title") }}
      </sbb-navigation-button>
      <sbb-navigation-link id="nav-section-3">
        {{ t("menu.authorization.title") }}
      </sbb-navigation-link>
    </sbb-navigation-marker>
  
    <sbb-navigation-section trigger="menu-section-1">
      <span slot="label">{{ t("menu.my-services.title") }}</span>
      <sbb-navigation-list>
        <span slot="label"></span>
        <sbb-navigation-button [routerLink]="['/services/ticket/damages']">
          {{ t("menu.my-services.damages-overview") }}
        </sbb-navigation-button>
        <sbb-navigation-button [routerLink]="['/services/ticket/overview']">
          {{ t("menu.my-services.tickets-overview") }}
        </sbb-navigation-button>
        <sbb-navigation-button [routerLink]="['/services/pinboard/overview']">
          {{ t("menu.my-services.pinboard") }}
        </sbb-navigation-button>
      </sbb-navigation-list>
    </sbb-navigation-section>
  </sbb-navigation>
  ```
2. inspect opened site

### Relevant log output

```shell
<body data-sbb-scroll-disabled style="overflow: hidden; position: relative; margin-inline-end: 15px; --sbb-scrollbar-width: 15px;">, this part gets deleted when i just close the menu with the X-Button.
```

**Comment by kyubisation** [comment]
Hello @nlueem 

I am not sure I fully understand you.
What you are describing seems to work fine with https://lyne-storybook.app.sbb.ch/iframe.html?args=&id=elements-sbb-navigation-sbb-navigation--with-navigation-section&viewMode=story
Can you maybe provide a working reproduction with e.g. StackBlitz?

**Comment by nlueem** [comment]
https://github.com/nlueem/test-nav, hope this helps too? after navigating to target you should see that the style is still on the body-element.

**Comment by kyubisation** [comment]
Ok, I see the problem.
Internally the problem is that the navigation is removed from the DOM before the animation event listener is called.
This is unexpected, because we don't expect the navigation to be removed from the DOM, but we should be able to fix this.
