### ISSUE TITLE
[Bug]: data-sbb-inert blocks interaction for dialogs

### ISSUE THREAD

**Issue by WalkingOS** [sbb-design-systems/lyne-components#2969]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### It affects the following packages

Components

### Which version of Lyne Components are you using

1.2.0

### Operating system

Windows 10

### Browser / Browser version

Chrome

### Input mode

None

### What happened?

the "data-sbb-inert" or "inert" attribute is blocking the interaction for new opened dialogs.

### Steps to reproduce the issue

1.  use a sbb-dialog is hierarchically at the top of the DOM with an action button.
2. The action button opens a new sbb-dialog, which is positioned hierarchically at the bottom of the DOM.
3. The newly opened dialog is displayed, but its interaction is blocked by the data-sbb-inert attribute of the first dialog.

**Comment by jeripeierSBB** [comment]
@dauriamarco Hi Marco, could we maybe look at this issue together? As once mentioned, I had ideas to refactor the current solution (as we also have the shadow DOM problem). Moreover, before changing anything, we should create a lot of (or at least some ;-)) tests (We talked already about that).
