### ISSUE TITLE
[Bug]: Search overlay IOS blank space

### ISSUE THREAD

**Issue by Acika00mk** [sbb-design-systems/lyne-components#2991]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### It affects the following packages

Components

### Which version of Lyne Components are you using

1.6.0

### Operating system

IOS 17

### Browser / Browser version

Safari 

### Input mode

Touch

### What happened?

When the search overlay is opened a scroll is executed and the location bar is minimising and we have a blank space at the bottom

### Steps to reproduce the issue

From iPhone version 17 
1. Open sbb.ch or https://dev-www.sbb.ch/de/reiseinformationen/bahnverkehrsinfo/betriebslage-stoerungen.html
2. Click on the search icon
3. Overlay is opened
4. Observe the bottom blank space, page content is shown as well 
![Screenshot 2024-08-07 at 11 32 58](https://github.com/user-attachments/assets/cd406d9a-e656-4195-8bf5-df60d373a9c9)
Link from video : https://sbb.sharepoint.com/:v:/r/sites/esta-web-design-systems/Freigegebene%20Dokumente/ESTA%20-%20WebEx/Screen%20Recording%202024-07-24%20at%2013.01.36.mov?csf=1&web=1&e=gzV22b

**Comment by jeripeierSBB** [comment]
Upstream Issue: https://flow.sbb.ch/browse/WEBEX-2950

**Comment by jeripeierSBB** [comment]
Could not be reproduced.
