### ISSUE TITLE
story: provide lean context config

### ISSUE THREAD

**Issue by jeripeierSBB** [sbb-design-systems/lyne-components#3010]
We want to provide defaults for the lean context.
We will do this programmatically by creating a function `isLean`, which checks whether the `<html>` element has the `sbb-lean` css class.
The default value for the relevant properties is set that way: `public accessor size: 's' | 'm' | 'l' = isLean() ? 's' : 'm'`;

**Comment by kyubisation** [comment]
I would say no for now, even if it is an inconvenience. My goal would be to define the default via CSS and not via js, but that would probably be part of the css refactoring.

**Comment by DavideMininni-Fincons** [comment]
Ok, then I can open a draft pr 👍 

another question: do we need some kind of testing/visual testing/something for Manuel? 
eg. on Storybook the default is usually overridden, so i have tested the behavior only via console; 
should I created a home-lean demo page? or specific stories for each component that I changed?

**Comment by kyubisation** [comment]
Hm, maybe as you suggested a home-lean demo page? I think that should be enough for now.
