### ISSUE TITLE
[Bug]: SSR - popover not showing up on click

### ISSUE THREAD

**Issue by feerglas** [sbb-design-systems/lyne-components#3012]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### It affects the following packages

Components

### Which version of Lyne Components are you using

1.7.0

### Operating system

MacOS 14.3

### Browser / Browser version

Chromium 127.0.6533.120

### Input mode

Mouse/Keyboard

### What happened?

When using SSR, popover does not show up on click.

It works perfectly without SSR.

### Steps to reproduce the issue

- open https://codesandbox.io/p/devbox/sbb-popover-hover-trigger-v575qq
- make sure the server is running, otherwise run npm start on the terminal.
- click on the popover trigger
- notice that the popover is not showing up

**Comment by feerglas** [comment]
@jeripeierSBB so fast 😎 i guess you have some sort of AI-Coder in your team who's creating a fix and a PR as soon as an issue is reported? ;)

**Comment by jeripeierSBB** [comment]
@feerglas pssst, don't tell anybody ;-). In this case, it was an easy fix. The main work was to create tests :D
