### ISSUE TITLE
[Feature request]: keep already set tabindex on buttons

### ISSUE THREAD

**Issue by stefan-schubert-sbb** [sbb-design-systems/lyne-components#3079]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/4) for an issue that matches the one I want to file, without success.

### Request type

Request for enhancement of a component

### It affects the following packages

Components

### Functionality

Actually button components set initially a tabindex to 0, but ignore already set tabindex in markup. Is it possible to recognize already set tabindex on button components?

**Comment by jeripeierSBB** [comment]
would it also work by setting inert attribute to the button component or it's parent in your case?

**Comment by stefan-schubert-sbb** [comment]
No, with inert a element is not focusable at all. I only want to exclude the element from the tabindex.

**Comment by jeripeierSBB** [comment]
We are sorry that we can't provide support in this case. We will close this issue for now.
