### ISSUE TITLE
[Bug]: Sticky Header covers Map Zoom Icons on Mobile 

### ISSUE THREAD

**Issue by RobinOpf** [sbb-design-systems/lyne-components#3091]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Accessibility

### It affects the following packages

Design Tokens

### Which version of Lyne Components are you using

1.9.0

### Operating system

Android

### Input mode

None

### What happened?

On mobile, the sticky header covers part of the map contrainer and its components when scrolling down on the main content of the page.

Stackblitz example: https://stackblitz.com/edit/sticky-header-covers-part-of-map-container-content?file=src%2Fmain.html

Video demo: https://github.com/user-attachments/assets/bf29bda3-14da-4294-a19f-cf72058c425a

### Steps to reproduce the issue

Setup: on mobile from top to bottom: a header, a map container with zoom buttons or another component on the top (right, left, middle not relevant), other page content
1. scroll/pull up the main content of the page halfway to the top, with half of the map still visible
2. map content will slide a small amount under the header, making buttons or content on the map less accessible

**Comment by sandrooco** [comment]
Hi @jeripeierSBB, we're seeing this issue on larger safari devices (iPad and up). As far as I've [seen in the source](https://github.com/sbb-design-systems/lyne-components/blob/main/src/elements/map-container/map-container.scss#L108), the `inset-block-start` is only applied up to the medium breakpoint. iPads don't match this breakpoint which probably causes the issue for us.

When adding the two lines from the media query to our global styles (which I would like to avoid), it works properly on iPads/Safari too.
Is there a way these two lines could be used for larger screens too?

Thanks in advance!
