### ISSUE TITLE
[Bug]: Button is above popup but has no z-index

### ISSUE THREAD

**Issue by Cyrill226** [sbb-design-systems/lyne-components#3118]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Accessibility

### It affects the following packages

Components

### Which version of Lyne Components are you using

1.11.3

### Operating system

MacOS

### Browser / Browser version

Google Chrome

### Input mode

Mouse/Keyboard

### What happened?

In our application "Knotenkenntnisse," we use Lyne alongside Editor.js as our editor library. This combination causes issues with the button styling in Lyne. Specifically, when a user opens a popup on a mobile device, the buttons appear above the popup, despite not having a defined z-index. This issue can be observed in the following example: [link](https://knotenkenntnisse-dev.app.sbb.ch/BN/scenarios/6081/editor)
If I use a normal HTML button this problem doesn't show up. This is why I'm reporting this bug here.

### Steps to reproduce the issue

1. Open up this [link](https://knotenkenntnisse-dev.app.sbb.ch/BN/scenarios/6081/editor)
2. Use a mobile screen size
3. Scroll to the bottom of the page, so you can see all 3 Lyne buttons
4. Click on the empty video or on one of the images, to display a "+" button
5. Click the "+" button and the popup shows up at the bottom of the page. now the buttons will be above the popup

**Comment by jeripeierSBB** [comment]
Hi @Cyrill226 
I don't have access to the provided Link. Could you create a simple reproduction on stackblitz?

<img width="376" alt="Bildschirmfoto 2024-09-25 um 08 58 11" src="https://github.com/user-attachments/assets/b97adc08-5060-4af3-b712-ce228069c906">

**Comment by Cyrill226** [comment]
Hi @jeripeierSBB 

Thank you for your response. In the meantime, I was able to resolve the issue in our app. However, I still find it strange that the problem occurred only with the Lyne SBB Button and not with a normal HTML button. Unfortunately, I cannot reproduce the issue on StackBlitz as it appeared in our application. Is it okay if I close the ticket? Otherwise, I can demonstrate the issue on my local machine.

**Comment by jeripeierSBB** [comment]
Thank you for re-checking! Yes, it's ok to close. In the current implementation, we need an absolutely positioned background, which generates a new context in stacking. But we have ideas to once get away from that solution :)
