### ISSUE TITLE
[Bug]: SSR-only -> sbb-header-link & sbb-header-button issues

### ISSUE THREAD

**Issue by feerglas** [sbb-design-systems/lyne-components#3128]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### It affects the following packages

Components

### Which version of Lyne Components are you using

1.12.0

### Operating system

MacOS 15.0

### Browser / Browser version

Chromium 128.0.6613.120

### Input mode

None

### What happened?

When using SSR, sbb-header-link and sbb-header-button have several issues:
- wrong spacings
- wrong color
- wrong hover-states incl. cursor

![Bildschirmfoto 2024-10-01 um 10 43 23](https://github.com/user-attachments/assets/0b243d4a-bad8-4457-88ac-f655dd8977c5)

### Steps to reproduce the issue

1. open https://codesandbox.io/p/devbox/lyne-header-issues-z5r9rv
2. make sure the server is running, otherwise run npm start on the terminal.
3. notice the various issues with the sbb-header-link and the sbb-header-button

**Comment by jeripeierSBB** [comment]
Same problem origin as #3127, caused by https://github.com/sbb-design-systems/lyne-components/commit/f3494636331ed2b1437816d57ffc94fe5d7a93f1

**Comment by feerglas** [comment]
an update of the peer dependencies resolved the issue
