### ISSUE TITLE
[Bug]: sbb-teaser accessibility problems

### ISSUE THREAD

**Issue by orsolya-gyovai** [sbb-design-systems/lyne-components#3173]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/4) for an issue that matches the one I want to file, without success.

### Request type

Request for enhancement of a component

### It affects the following packages

Components

### Functionality

Dear All,

We need some adjustment (or new feature?) for the sbb-teaser:
[https://feature-sbbch-20354-discount-teaserset.dev-www.sbb.ch/de/angebote/halbtax-plus-kaufen-test-1]
This is now implemented with the 'sbb-teaser'. The problem with this is that after focusing on the element and then pressing the arrow key, the screen reader does not output the detailed describing text below the title, but the title of the following tile is output.
The needed component should behave like the 'sbb-card-link' tag, but should contain an image.
Jeremias and Lennox have already discussed the problem, but but we can have a quick look together, so that it is easier to understand what I mean :-)

**Comment by LEGlism** [comment]
its the Teaser Component of lyne.

**Comment by jeripeierSBB** [comment]
Should probably implemented like the sbb-card. As it is a breaking change I assign the issue to the next major version.
