### ISSUE TITLE
[Bug]: sbb-autocomplete does not stop keyboard event on pressing enter

### ISSUE THREAD

**Issue by stefan-schubert-sbb** [sbb-design-systems/lyne-components#3239]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### It affects the following packages

Components

### Input mode

Mouse/Keyboard

### What happened?

The propagation/default action of the keyboard event on selecting a auto complete list item using the enter key is not stopped.

Expected behavior should be to stop this event to prevent further form actions.

### Steps to reproduce the issue

1. trigger auto complete drop down by focusing a auto complete input
2. selecting a item using the arrow keys
3. select a item using enter

**Comment by kyubisation** [comment]
![image](https://github.com/user-attachments/assets/b3850151-568a-45cb-853b-1f1316e04707)

In the Enter case, we should call `event.preventDefault()` and add a test.

**Comment by stefan-schubert-sbb** [comment]
I have one addition: On selection of an item no change event is triggered. It is possible to fix this issue within this bug?
