### ISSUE TITLE
[Bug]: SBB Menu is behind SBB Map Container

### ISSUE THREAD

**Issue by Cyrill226** [sbb-design-systems/lyne-components#3265]
### Preflight Checklist

- [X] I have read the [Contributing Guidelines](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CONTRIBUTING.md) for this project.
- [X] I agree to follow the [Code of Conduct](https://github.com/sbb-design-systems/lyne-components/blob/main/docs/CODE_OF_CONDUCT.md) that this project adheres to.
- [X] I have searched the [issue tracker](https://github.com/orgs/sbb-design-systems/projects/4) for an issue that matches the one I want to file, without success.

### Bug type

Functionality

### It affects the following packages

Components

### Which version of Lyne Components are you using

1.15.0

### Operating system

MacOS

### Browser / Browser version

Google Chrome

### Input mode

Mouse/Keyboard

### What happened?

In our app "Knotenkenntnisse," we utilize the SBB map container component. Within the UI elements, we use the SBB menu component. We have identified a potential issue when these components are used together on mobile screens.

In our app, the map is displayed to almost the full height of the screen, with content at the bottom that can be scrolled over the map. When we open a popup containing an SBB menu directly over the map, the menu appears under the main content, rendering it unusable.

To illustrate this issue, I created an example on Stackblitz. Due to the limited size of the map container, I had to include numerous buttons inside the menu to demonstrate the problem effectively.

Unfortunately, I cannot provide a link to our app, as access is restricted and managed via AD groups.

<img width="511" alt="Bildschirmfoto 2024-12-02 um 10 40 28" src="https://github.com/user-attachments/assets/30b7a770-9852-40e0-a0d5-88b14baae015">

https://stackblitz.com/edit/stackblitz-starters-83j6ee?file=package.json

### Steps to reproduce the issue

1. Click the "open" button
2. Now you can see the map container over the SBB menu

**Comment by dauriamarco** [comment]
Thank you for your detailed bug report and for providing the Stackblitz example to illustrate the issue.

A potential immediate solution to address this problem would be to position the `sbb-menu` component outside of the map-container. By doing so, you can prevent the map’s layers or content from interfering with the menu’s visibility and usability.

Looking ahead, once the Popover API becomes fully available, we plan to explore its implementation. This would allow us to make the `sbb-menu` more stable and resilient in scenarios like this, ensuring seamless integration with various container components.
